name: Release to TestPyPI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish-to-testpypi:
    runs-on: ubuntu-latest
    environment: testpypi
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Check dist metadata
        run: |
          pip install twine
          twine check dist/*

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true