name: Release to TestPyPI

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*-test*"
      - "v*.*.*-alpha*"
      - "v*.*.*-beta*"

permissions:
  contents: read
  id-token: write

jobs:
  publish-to-testpypi:
    runs-on: ubuntu-latest
    environment: testpypi
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/